version: "3.8"

services:
  angular:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ../src:/app/src
      - ../dist:/app/dist
    depends_on:
      - json-server

  json-server:
    build:
      context: ../
      dockerfile: docker/Dockerfile.server
    ports:
      - "3000:3000"
    volumes:
      - ../:/data
#
# We can also build the file like so :
# services:
#   angular:
#     image: # image name
#     ports: # port mapping
#
#   json-server:
#     image: # image name
#     ports: # port mapping
#
# volumes:
#   stack-volume:
#
