FROM node:16-slim

WORKDIR /usr/src/app

RUN mkdir -p /database

COPY db.json /database/db.json

RUN npm install -g json-server

EXPOSE 3000

VOLUME /database

CMD ["json-server", "--watch", "/data/db.json"]
